import Huckleberry from "../assets/images/Huckleberry.jpg"
import HuckleberryJalapeno from "../assets/images/Huckleberry-Jalapeno.jpg"
import HuckleberryChocolate from "../assets/images/Huckleberry-Chocolate.jpg"
import AppleMaple from "../assets/images/Apple-Maple.jpg"
import FlatheadCherry from "../assets/images/Flathead-Cherry.jpg"
import FlatheadCherryJalapeno from "../assets/images/Flathead-cherry-jalapeno-w.jpg"
import FlatheadCherryChocolate from "../assets/images/Flathead-Cherry-Chocolate.jpg"
import PineappleCoconut from "../assets/images/Pineapple-Coconut.jpg"
import PineappleJalapeno from "../assets/images/Pineapple-Jalapeno.jpg"
import Raspberry from "../assets/images/Raspberry.jpg"
import RaspberryJalapeno from "../assets/images/Raspberry-Jalapeno.jpg"
import RedPepperJalapenoHot from "../assets/images/Red-Pepper-Jalapeno-Hot.jpg"
import RedPepperJalapenoMild from "../assets/images/Red-Pepper-Jalapeno-Mild.jpg"

const SHOP_DATA = [
  {
    id: 1,
    title: "Huckleberry",
    description: "4oz Huckleberry is the favorite of many.",
    size: "4oz",
    imageUrl: Huckleberry,
    price: 8,
    category: "huckleberry",
  },
  {
    id: 2,
    title: "Huckleberry",
    description: "8oz Huckleberry is the favorite of many.",
    size: "8oz",
    imageUrl: Huckleberry,
    price: 12,
    category: "huckleberry",
  },
  {
    id: 3,
    title: "Huckleberry",
    description: "12oz Huckleberry is the favorite of many.",
    size: "12oz",
    imageUrl: Huckleberry,
    price: 15,
    category: "huckleberry",
  },
  {
    id: 4,
    title: "Huckleberry Jalapeno",
    description: "Best got better with spicy jalapeno",
    size: "4oz",
    imageUrl: HuckleberryJalapeno,
    price: 8,
    category: "huckleberry-jalapeno",
  },
  {
    id: 5,
    title: "Huckleberry Jalapeno",
    description: "8oz of the best got better with spicy jalapeno",
    size: "8oz",
    imageUrl: HuckleberryJalapeno,
    price: 12,
    category: "huckleberry-jalapeno",
  },
  {
    id: 6,
    title: "Huckleberry Jalapeno",
    description: "12oz of the best got better with spicy jalapeno",
    size: "12oz",
    imageUrl: HuckleberryJalapeno,
    price: 15,
    category: "huckleberry-jalapeno",
  },
  {
    id: 7,
    title: "Huckleberry Chocolate",
    description: "4oz of the best for chocolate lovers",
    size: "4oz",
    imageUrl: HuckleberryChocolate,
    price: 8,
    category: "huckleberry-chocolate",
  },
  {
    id: 8,
    title: "Huckleberry Chocolate",
    description: "8oz of the best for chocolate lovers",
    size: "8oz",
    imageUrl: HuckleberryChocolate,
    price: 12,
    category: "huckleberry-chocolate",
  },
  {
    id: 9,
    title: "Huckleberry Chocolate",
    description: "12oz of the best for chocolate lovers",
    size: "12oz",
    imageUrl: HuckleberryChocolate,
    price: 15,
    category: "huckleberry-chocolate",
  },
  {
    id: 10,
    title: "Apple Maple",
    description: "4oz of better than syrup",
    size: "4oz",
    imageUrl: AppleMaple,
    price: 8,
    category: "apple-maple",
  },
  {
    id: 11,
    title: "Apple Maple",
    description: "8oz of better than syrup",
    size: "8oz",
    imageUrl: AppleMaple,
    price: 12,
    category: "apple-maple",
  },
  {
    id: 12,
    title: "Apple Maple",
    description: "12oz of better than syrup",
    size: "12oz",
    imageUrl: AppleMaple,
    price: 15,
    category: "apple-maple",
  },
  {
    id: 13,
    title: "Flathead Cherry",
    description: "Local from the around the lake",
    size: "4oz",
    imageUrl: FlatheadCherry,
    price: 8,
    category: "flathead-cherry",
  },
  {
    id: 14,
    title: "Flathead Cherry",
    description: "8oz Local from the around the lake",
    size: "8oz",
    imageUrl: FlatheadCherry,
    price: 12,
    category: "flathead-cherry",
  },
  {
    id: 15,
    title: "Flathead Cherry",
    description: "12oz Local from the around the lake",
    size: "12oz",
    imageUrl: FlatheadCherry,
    price: 15,
    category: "flathead-cherry",
  },
  {
    id: 16,
    title: "Flathead Cherry Jalapeno",
    description: "4oz of this in your cherry pie",
    size: "4oz",
    imageUrl: FlatheadCherryJalapeno,
    price: 8,
    category: "flathead-cherry-jalapeno",
  },
  {
    id: 17,
    title: "Flathead Cherry Jalapeno",
    description: "8oz of this in your cherry pie",
    size: "8oz",
    imageUrl: FlatheadCherryJalapeno,
    price: 12,
    category: "flathead-cherry-jalapeno",
  },
  {
    id: 18,
    title: "Flathead Cherry Jalapeno",
    description: "12oz of this in your cherry pie",
    size: "12oz",
    imageUrl: FlatheadCherryJalapeno,
    price: 15,
    category: "flathead-cherry-jalapeno",
  },
  {
    id: 19,
    title: "Flathead Cherry Chocolate",
    description: "4oz cherry for chocolate lovers",
    imageUrl: FlatheadCherryChocolate,
    size: "4oz",
    price: 8,
    category: "flathead-cherry-chocolate",
  },
  {
    id: 20,
    title: "Flathead Cherry Chocolate",
    description: "8oz cherry for chocolate lovers",
    imageUrl: FlatheadCherryChocolate,
    size: "8oz",
    price: 12,
    category: "flathead-cherry-chocolate",
  },
  {
    id: 21,
    title: "Flathead Cherry Chocolate",
    description: "12oz cherry for chocolate lovers",
    imageUrl: FlatheadCherryChocolate,
    size: "12oz",
    price: 15,
    category: "flathead-cherry-chocolate",
  },
  {
    id: 22,
    title: "Pineapple Coconut",
    description: "4oz vacation in a jar",
    imageUrl: PineappleCoconut,
    size: "4oz",
    price: 8,
    category: "pineapple-coconut",
  },
  {
    id: 23,
    title: "Pineapple Coconut",
    description: "8oz vacation in a jar",
    imageUrl: PineappleCoconut,
    size: "8oz",
    price: 12,
    category: "pineapple-coconut",
  },
  {
    id: 24,
    title: "Pineapple Coconut",
    description: "12oz vacation in a jar",
    imageUrl: PineappleCoconut,
    size: "12oz",
    price: 15,
    category: "pineapple-coconut",
  },
  {
    id: 25,
    title: "Pineapple Jalapeno",
    description: "4oz of spicy vacation in a jar",
    imageUrl: PineappleJalapeno,
    size: "4oz",
    price: 8,
    category: "pineapple-jalapeno",
  },
  {
    id: 26,
    title: "Pineapple Jalapeno",
    description: "8oz of spicy vacation in a jar",
    imageUrl: PineappleJalapeno,
    size: "8oz",
    price: 12,
    category: "pineapple-jalapeno",
  },
  {
    id: 27,
    title: "Pineapple Jalapeno",
    description: "12oz of spicy vacation in a jar",
    imageUrl: PineappleJalapeno,
    size: "12oz",
    price: 15,
    category: "pineapple-jalapeno",
  },
  {
    id: 28,
    title: "Raspberry",
    description: "4oz of smoothness",
    imageUrl: Raspberry,
    size: "4oz",
    price: 8,
    category: "raspberrry",
  },
  {
    id: 29,
    title: "Raspberry",
    description: "8oz of smoothness",
    imageUrl: Raspberry,
    size: "8oz",
    price: 12,
    category: "raspberrry",
  },
  {
    id: 30,
    title: "Raspberry",
    description: "12oz of smoothness",
    imageUrl: Raspberry,
    size: "12oz",
    price: 15,
    category: "raspberrry",
  },
  {
    id: 31,
    title: "Raspberry Jalapeno",
    description: "4oz of smoothness",
    imageUrl: RaspberryJalapeno,
    size: "4oz",
    price: 8,
    category: "raspberrry-jalapeno",
  },
  {
    id: 32,
    title: "Raspberry Jalapeno",
    description: "8oz of smoothness",
    imageUrl: RaspberryJalapeno,
    size: "8oz",
    price: 12,
    category: "raspberrry-jalapeno",
  },
  {
    id: 33,
    title: "Raspberry Jalapeno",
    description: "12oz of smoothness",
    imageUrl: RaspberryJalapeno,
    size: "12oz",
    price: 15,
    category: "raspberrry-jalapeno",
  },
  {
    id: 34,
    title: "Red Pepper Jalapeno - Hot",
    description: "4oz of the hottest we have",
    imageUrl: RedPepperJalapenoHot,
    size: "4oz",
    price: 8,
    category: "red-pepper-jalapeno-hot",
  },
  {
    id: 35,
    title: "Red Pepper Jalapeno - Hot",
    description: "8oz of the hottest we have",
    imageUrl: RedPepperJalapenoHot,
    size: "8oz",
    price: 12,
    category: "red-pepper-jalapeno-hot",
  },
  {
    id: 36,
    title: "Red Pepper Jalapeno - Hot",
    description: "12oz of the hottest we have",
    imageUrl: RedPepperJalapenoHot,
    size: "12oz",
    price: 15,
    category: "red-pepper-jalapeno-hot",
  },
  {
    id: 37,
    title: "Red Pepper Jalapeno - Mild",
    description: "4oz of the hottest we have",
    imageUrl: RedPepperJalapenoMild,
    size: "4oz",
    price: 8,
    category: "red-pepper-jalapeno-mild",
  },
  {
    id: 38,
    title: "Red Pepper Jalapeno - Mild",
    description: "8oz of the hottest we have",
    imageUrl: RedPepperJalapenoMild,
    size: "8oz",
    price: 12,
    category: "red-pepper-jalapeno-mild",
  },
  {
    id: 39,
    title: "Red Pepper Jalapeno - Mild",
    description: "12oz of the hottest we have",
    imageUrl: RedPepperJalapenoMild,
    size: "12oz",
    price: 15,
    category: "red-pepper-jalapeno-mild",
  },
]

// const PRODUCT_IMAGES = [
//   {
//     id: 1,
//     imageUrl: Huckleberry,
//   },
//   {
//     id: 2,
//     imageUrl: HuckleberryJalapeno,
//   },
//   {
//     id: 3,
//     imageUrl: HuckleberryChocolate,
//   },
//   {
//     id: 4,
//     imageUrl: AppleMaple,
//   },
//   {
//     id: 5,
//     imageUrl: FlatheadCherry,
//   },
//   {
//     id: 7,
//     imageUrl: FlatheadCherryJalapeno,
//   },
//   {
//     id: 8,
//     imageUrl: FlatheadCherryChocolate,
//   },
//   {
//     id: 8,
//     imageUrl: PineappleCoconut,
//   },
//   {
//     id: 8,
//     imageUrl: PineappleJalapeno,
//   },
//   {
//     id: 8,
//     imageUrl: Raspberry,
//   },
//   {
//     id: 8,
//     imageUrl: RaspberryJalapeno,
//   },
//   {
//     id: 8,
//     imageUrl: RedPepperJalapenoMild,
//   },
//   {
//     id: 8,
//     imageUrl: RedPepperJalapenoHot,
//   },
// ]

export default SHOP_DATA
